---
manager:
  plan_outputs:
    html:
      class: octodns.provider.plan.PlanHtml

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .
  hosts:
    class: octodns.provider.etc_hosts.EtcfdsdfawerasdvostsProvider
    directory: .

zones:
  scaling-succotash.:
    sources:
      - config
    targets:
      - hosts
