name: octodns-sync

on:
  # Test config on default pull_request activity types
  # (Remember type is called action, in the event payload)
  pull_request:
    types: [opened, synchronize, reopened]
  # Also run when manually triggered
  workflow_dispatch:

jobs:
  publish:
    name: Test DNS config (${{ github.event.action }})
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v2
      - name: Run octodns-sync
        uses: solvaholic/octodns-sync@issue57
        with:
          config_path: test-config.yaml
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
      - name: Run octodns-sync again
        uses: solvaholic/octodns-sync@issue57
        with:
          config_path: test-config.yaml
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
