name: octodns-sync

on:
  # Test config on default pull_request activity types
  # (Remember type is called action, in the event payload)
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish:
    name: Test DNS config (${{ github.event.action }})
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout refs/pull/${{ github.event.number }}/head
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/head
      - name: Run octodns-sync
        uses: solvaholic/octodns-sync@issue51
        with:
          config_path: test-config.yaml
          add_pr_comment: 'Yes'
          pr_comment_token: '${{ github.token }}'
