on:
  # Run when manually triggered
  workflow_dispatch:
    inputs:
      # User inputs the octodns release to use, for example `v0.9.12`
      version:
        description: 'octodns release to use, for example v0.9.12'
        required: true

defaults:
  run:
    shell: bash

jobs:
  on-runner:
    runs-on: ubuntu-20.04
    steps:
      # Check out this repository at the same ref that triggered
      # this workflow run
      - uses: actions/checkout@v2

      # Run octodns to test current config
      - name: Test current configuration
        id: octodns-test
        uses: solvaholic/octodns-sync@issue50
        with:
          config_path: test-config.yaml
          doit: 'no'
          add_pr_comment: 'no'
          octodns_ref: ${{ github.event.inputs.version }}
          pr_comment_token: 'not set'

      # Check that :point_up: output
      - name: Check octodns-sync output
        run: cat $GITHUB_WORKSPACE/octodns-sync.plan