on:
  # Run when manually triggered
  workflow_dispatch:
    inputs:
      # User inputs the octodns release to use, for example `v0.9.12`
      version:
        description: 'octodns release to use, for example v0.9.12'
        default: 'v0.9.12'
        required: true
  # Run on pull request open, reopen, and synchronize
  pull_request:
     branches: [main]

defaults:
  run:
    shell: bash

jobs:
  on-runner:
    runs-on: ubuntu-20.04
    outputs:
      ref: ${{ steps.pick-ref.outputs.octodns_ref }}
    steps:
      # Pick a value for octodns_ref
      # Use input if workflow_dispatch, else default to v0.9.12
      - id: pick-ref
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            _ref="${{ github.event.inputs.version }}"
          else
            _ref="v0.9.12"
          fi
          echo "::set-output name=octodns_ref::${_ref}"
      # Check out this repository at the same ref that triggered
      # this workflow run
      - uses: actions/checkout@v2
      # Run octodns to test current config
      - name: Test current configuration
        id: octodns-test
        uses: solvaholic/octodns-sync@issue50
        with:
          config_path: test-config.yaml
          doit: 'no'
          add_pr_comment: 'Yes'
          octodns_ref: ${{ steps.pick-ref.outputs.octodns_ref }}
          pr_comment_token: ${{ secrets.PAT }}

      # Check that :point_up: output
      - name: Check octodns-sync output
        run: cat $GITHUB_WORKSPACE/octodns-sync.plan